# Generated by Django 3.2.4 on 2021-07-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labname', models.CharField(max_length=100, null=True)),
                ('labaddress', models.CharField(max_length=100, null=True)),
                ('labtests', models.CharField(max_length=100, null=True)),
                ('gst', models.IntegerField(null=True)),
                ('file', models.FileField(null=True, upload_to='documents')),
            ],
            options={
                'verbose_name_plural': 'labupdates',
            },
        ),
    ]
