# Generated by Django 3.2.4 on 2021-07-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labadmin',
            name='lablocation',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
