# Generated by Django 3.2.4 on 2021-07-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_auto_20210708_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='labadmin',
            name='is_admin',
            field=models.BooleanField(null=True),
        ),
    ]
