# Generated by Django 3.2.4 on 2021-07-10 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_labadmin_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='labadmin',
            name='adminpssword',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labadmin',
            name='adminusername',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
