# Generated by Django 3.2.4 on 2021-07-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_auto_20210710_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labadmin',
            old_name='adminusername',
            new_name='adminemail',
        ),
    ]
