# Generated by Django 3.2.4 on 2021-06-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_newuser_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={'verbose_name_plural': 'UserDetails'},
        ),
    ]
