# Generated by Django 3.2.4 on 2021-06-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_newuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='file',
        ),
    ]
