# Generated by Django 3.2.4 on 2021-06-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newuser',
        ),
    ]
